import tout from "../assets/logo.jpg";

const servicesData = [
  {
    image: tout,
    name: "Teinture des sourcils",
    time: "30min",
    price: "15 €",
    category: "Beauté Du Regard",
  },
  {
    image: tout,
    name: "Rehaussement de cils",
    time: "1 h",
    price: "50 €",
    category: "Beauté Du Regard",
  },
  {
    image: tout,
    name: "Restructuration des sourcils",
    time: "30min",
    price: "10 €",
    category: "Beauté Du Regard",
  },
  {
    image: tout,
    name: "Brow Lift",
    time: "1 h",
    price: "35 €",
    category: "Beauté Du Regard",
  },
  {
    image: tout,
    name: "Teinture des cils",
    time: "20 min",
    price: "10 €",
    category: "Beauté Du Regard",
  },
  {
    image: tout,
    name: "Pose de vernis semi-permanent sur les pieds",
    time: "30 min ",
    price: " 30 €",
    category: "Beauté des mains et pieds",
  },
  {
    image: tout,
    name: "Beauté des pieds et pose de vernis semi-permanent",
    time: "1h",
    price: " 30 €",
    category: "Beauté des mains et pieds",
  },
  {
    image: tout,
    name: "Dépose de vernis semi-permanent sur les pieds",
    time: "20min",
    price: " 10 €",
    category: "Beauté des mains et pieds",
  },
  {
    image: tout,
    name: "Soin des pieds",
    time: "1h",
    price: " 30 €",
    category: "Beauté des mains et pieds",
  },
  {
    image: tout,
    name: "Limage et pose de vernis sur les pieds",
    time: "30min",
    price: " 30 €",
    category: "Beauté des mains et pieds",
  },
  {
    image: tout,
    name: "Beauté des pieds et pose de vernis semi-permanent",
    time: "1h",
    price: " 30 €",
    category: "Beauté des mains et pieds",
  },
  {
    image: tout,
    name: "Beauté des pieds Spa",
    time: "45min",
    price: " 30 €",
    category: "Beauté des mains et pieds",
  },
  {
    image: tout,
    name: "Beauté des pieds Spa et pose de vernis semi-permanent",
    time: "1h 15min",
    price: " 50 €",
    category: "Beauté des mains et pieds",
  },
  {
    image: tout,
    name: "Microblading des sourcils",
    time: "1 h 30 min",
    price: "200 €",
    category: "Maquillage permanent",
  },
  {
    image: tout,
    name: "Microshading des sourcils",
    time: "2 h",
    price: "170 €",
    category: "Maquillage permanent",
  },
  {
    image: tout,
    name: "Maquillage semi-permanent - Grain de beauté",
    time: "15 min",
    price: "30 €",
    category: "Maquillage permanent",
  },
  // {
  //   image: tout,
  //   name: "Maquillage semi-permanent - Sourcils",
  //   time: "2 h",
  //   price: "200 €",
  //   category: "Maquillage permanent",
  // },
  {
    image: tout,
    name: "Maquillage semi-permanent - Lèvres",
    time: "2 h",
    price: "200 €",
    category: "Maquillage permanent",
  },
  {
    image: tout,
    name: "Retouche de maquillage semi-permanent (3 semaines à 1 mois)",
    time: "1 h",
    price: "50 €",
    category: "Maquillage permanent",
  },
  {
    image: tout,
    name: "Retouche de maquillage semi-permanent (8 mois)",
    time: "1 h",
    price: "80 €",
    category: "Maquillage permanent",
  },
  {
    image: tout,
    name: "Retouche de maquillage semi-permanent (1 an)",
    time: "1 h",
    price: "100 €",
    category: "Maquillage permanent",
  },
  {
    image: tout,
    name: "Neutralisation du sourcil",
    time: "1 h",
    price: "90 €",
    category: "Maquillage permanent",
  },
  {
    image: tout,
    name: "Détatouage a partir de 50€",
    time: "30 min",
    price:" 50 €",
    category: "Maquillage permanent",
  },
  {
    image: tout,
    name: "Lèvre supérieure",
    time: "10 min",
    price: "5 €",
    category: "Épilation à la cire",
  },
  {
    image: tout,
    name: "Menton",
    time: "10 min",
    price: "10 €",
    category: "Épilation à la cire",
  },
  {
    image: tout,
    name: "Sourcils",
    time: "10 min",
    price: "10 €",
    category: "Épilation à la cire",
  },
  {
    image: tout,
    name: "Sourcils - Création de ligne",
    time: "20 min",
    price: "10 €",
    category: "Épilation à la cire",
  },
  {
    image: tout,
    name: "Sourcils - Entretien",
    time: "15 min",
    price: "10 €",
    category: "Épilation à la cire",
  },
  {
    image: tout,
    name: "Visage complet",
    time: "20 min",
    price: "30 €",
    category: "Épilation à la cire",
  },
  {
    image: tout,
    name: "Aisselles",
    time: "10 min",
    price: "15 €",
    category: "Épilation à la cire",
  },
  {
    image: tout,
    name: "Avant-bras",
    time: "20 min",
    price: "20 €",
    category: "Épilation à la cire",
  },
  {
    image: tout,
    name: "Bras complets",
    time: "30 min",
    price: "30 €",
    category: "Épilation à la cire",
  },
  {
    image: tout,
    name: "Épilation à la cire des sourcils - Création de ligne",
    time: "20 min",
    price: "15 €",
    category: "Épilation à la cire",
  },
  {
    image: tout,
    name: "Extensions de cils « Pose cil à cil »",
    time: "2 h",
    price: "50 €",
    category: "Extension",
  },
  {
    image: tout,
    name: "Extensions de cils « Pose volume russe légère » de 3D à 5D",
    time: "2 h",
    price: "50 €",
    category: "Extension",
  },
  {
    image: tout,
    name: "Extensions de cils « Pose 6D »",
    time: "2 h",
    price: "60 €",
    category: "Extension",
  },
  {
    image: tout,
    name: "Extensions de cils « Pose volume russe » 7D",
    time: "2h 30min",
    price: "70 €",
    category: "Extension",
  },
  {
    image: tout,
    name: "Extensions de cils « Pose volume russe » du 8D au 10D",
    time: "2h 30min",
    price: " 80 €",
    category: "Extension",
  },
  {
    image: tout,
    name: "Remplissage des extensions de cils",
    time: "1 h 30 min",
    price: "35 €",
    category: "Extension",
  },
  {
    image: tout,
    name: "Dépose d'extensions de cils",
    time: "1 h",
    price: "20 €",
    category: "Extension",
  },
  {
    image: tout,
    name: "Teinture des sourcils",
    time: "30 min",
    price: "15 €",
    category: "Beauté Du Regard",
  },
  {
    image: tout,
    name: "Rehaussement de cils",
    time: "1h",
    price: "50 €",
    category: "Beauté Du Regard",
  },
  {
    image: tout,
    name: "Rehaussement de cils avec teinture",
    time: "1h 30min",
    price: "60 €",
    category: "Beauté Du Regard",
  },
  {
    image: tout,
    name: "Visage complet",
    time: "",
    price: "85 €",
    category: "Épilation définitive laser",
  },
  {
    image: tout,
    name: "Inter sourcil",
    time: "",
    price: "15 €",
    category: "Épilation définitive laser",
  },
  {
    image: tout,
    name: "Cou",
    time: "",
    price: "30 €",
    category: "Épilation définitive laser",
  },
  {
    image: tout,
    name: "Joues",
    time: "",
    price: "30 €",
    category: "Épilation définitive laser",
  },
  {
    image: tout,
    name: "Pattes",
    time: "",
    price: "30 €",
    category: "Épilation définitive laser",
  },
  {
    image: tout,
    name: "Front",
    time: "",
    price: "30 €",
    category: "Épilation définitive laser",
  },

  {
    image: tout,
    name: "Lèvre supérieure",
    time: "",
    price: "30 €",
    category: "Épilation définitive laser",
  },
  {
    image: tout,
    name: "Aisselles",
    time: "",
    price: "30 €",
    category: "Épilation définitive laser",
  },
  {
    image: tout,
    name: "Avant bras + mains",
    time: "",
    price: "70 €",
    category: "Épilation définitive laser",
  },
  {
    image: tout,
    name: "Bras entiers + mains",
    time: "",
    price: "100 €",
    category: "Épilation définitive laser",
  },
  {
    image: tout,
    name: "Mains",
    time: "",
    price: "30 €",
    category: "Épilation définitive laser",
  },
  {
    image: tout,
    name: "Doigts",
    time: "",
    price: "15 €",
    category: "Épilation définitive laser",
  },
  {
    image: tout,
    name: "Dos",
    time: "",
    price: "145 €",
    category: "Épilation définitive laser",
  },
  {
    image: tout,
    name: "Ligne ombilicale",
    time: "",
    price: "30 €",
    category: "Épilation définitive laser",
  },
  {
    image: tout,
    name: "Aréoles mammaires",
    time: "",
    price: "20 €",
    category: "Épilation définitive laser",
  },
  {
    image: tout,
    name: "Ventre",
    time: "",
    price: "50 €",
    category: "Épilation définitive laser",
  },
  {
    image: tout,
    name: "Demi-jambes + pieds",
    time: "",
    price: "100 €",
    category: "Épilation définitive laser",
  },
  {
    image: tout,
    name: "Jambes complètes + pieds",
    time: "",
    price: "185 €",
    category: "Épilation définitive laser",
  },
  {
    image: tout,
    name: "Cuisses",
    time: "",
    price: "100 €",
    category: "Épilation définitive laser",
  },
  {
    image: tout,
    name: "Maillot simple",
    time: "",
    price: "30 €",
    category: "Épilation définitive laser",
  },
  {
    image: tout,
    name: "Maillot échancré",
    time: "",
    price: "45 €",
    category: "Épilation définitive laser",
  },
  {
    image: tout,
    name: "Maillot brésilien",
    time: "",
    price: "55 €",
    category: "Épilation définitive laser",
  },
  {
    image: tout,
    name: "Maillot intégral",
    time: "",
    price: "70 €",
    category: "Épilation définitive laser",
  },
  {
    image: tout,
    name: "Sillons inter fessiers",
    time: "",
    price: "30 €",
    category: "Épilation définitive laser",
  },
  {
    image: tout,
    name: "Fesses",
    time: "",
    price: "50 €",
    category: "Épilation définitive laser",
  },
];
export default servicesData;
